### ISSUE TITLE
Hizova - Ukol 13 + 14

### ISSUE THREAD

**Issue by khizova** [khizova/python-032021#1]
https://github.com/khizova/python-032021/blob/master/Ukoly/13_Kvalita_Cementu.py
https://github.com/khizova/python-032021/blob/master/Ukoly/14_Ryby.py

@pesikj

**Comment by pesikj** [comment]
Ahoj Katko, super :-)

**Comment by pesikj** [comment]
Můžeš uzavřít toto issue.

**Comment by khizova** [comment]
Ahoj Jirko, díky :)
