### ISSUE TITLE
Úkoly 16-22

### ISSUE THREAD

**Issue by khizova** [khizova/python-032021#2]
Ahoj Jirko, posielam posledné úkoly. Díky :) @pesikj

https://github.com/khizova/python-032021/blob/master/Ukoly/16_Otazky_Na_Python.py
https://github.com/khizova/python-032021/blob/master/Ukoly/17_KNearestNeighbors_1.py
https://github.com/khizova/python-032021/blob/master/Ukoly/18_KNearestNeighbors_2.py
https://github.com/khizova/python-032021/blob/master/Ukoly/19_Feature_Importance.py
https://github.com/khizova/python-032021/blob/master/Ukoly/20_Auto.py
https://github.com/khizova/python-032021/blob/master/Ukoly/21_Silhouette.py
https://github.com/khizova/python-032021/blob/master/Ukoly/22_MNIST.py

**Comment by pesikj** [comment]
Ahoj Katko, koukám správně, že úkol 15 jsi přeskočila? (Není nutné ho dělat, jen se ptám, abych tě neošidil :-) ).

**Comment by pesikj** [comment]
U úkolu 19 máš napsáno, že _"klesne hodnota f1_score o 25%"_. To přesně nevím, co tím myslíš. Jestli tomu dobře rozumím, tak šlo o pokles z 0,928 na 0,753, což je rozdíl cca. 0,18. Jinak ještě menší poznámka - v tomto případě bychom správně neměli mluvit o poklesu v procentech, ale v procentních bodech (ale to mají kolikrát špatně i novináři).

**Comment by pesikj** [comment]
U úkolu 22 bys dosáhla trochu lepších výsledků s 10 clustery.

![image](https://user-images.githubusercontent.com/15179154/145722694-c43cb961-fb5f-4d42-b366-3a61eae6ba6d.png)

**Comment by pesikj** [comment]
Jinak jsem prošel všechny úkoly a vše je v pořádku, kromě poznámek výše. Připisuji ti tedy 7 bodů :-)

**Comment by khizova** [comment]
Ahoj Jirko,

díky za feedback, mám to upravené.

15 som naozaj preskočila :)

Vďaka za fajn kurz!
